add_subdirectory(bk_ps)
add_subdirectory(bk_rtos)
add_subdirectory(bk_common)
add_subdirectory(bk_init)
add_subdirectory(avdk_utils)
add_subdirectory(release)
add_subdirectory(bk_wifi)
add_subdirectory(bk_wifi_driver)
add_subdirectory(lwip_intf_v2_1)
add_subdirectory(utf8)
add_subdirectory(bk_startup)
add_subdirectory(easy_log)
add_subdirectory(bk_pm)
add_subdirectory(bk_system)
add_subdirectory(bk_peripheral)
