# ##############################################################################
# bk_python.cmake
#
# Helper for running Beken bk_sdk python tools during the build.
#
# The bk_sdk scripts (bk_prebuild.py, bk_curr_project.py, ...) read a handful
# of variables via os.getenv() and import modules from tools/env_tools.  Those
# are not present in the NuttX build environment, so every invocation needs the
# same environment injected.  bk_add_python_command() wraps that boilerplate:
# it sources the env_setup.sh shell script generated by environment.py
# (see chips/CMakeLists.txt: add_custom_command / environment_setup_helper)
# to populate the bk_sdk variables, then runs the tool under bash.
#
# Usage:
#   bk_add_python_command(
#       OUTPUT   <file> [<file> ...]     # generated file(s); parent dirs auto-created
#       SCRIPT   <path/to/tool.py>       # python script to run
#       [ARGS    <arg> ...]              # positional args passed to the script
#       [DEPENDS <file/target> ...]      # extra build dependencies
#       [EXTRA_PYTHONPATH <dir> ...]     # dirs appended after bk_py_libs
#       [COMMENT "..."]                  # progress message
#   )
#
# Required variables in the calling scope (set in chips/CMakeLists.txt before
# the enclosing add_subdirectory()): BEKEN_SOC_NAME, NUTTX_CHIP_ABS_DIR,
# NUTTX_BOARD_ABS_DIR, NUTTX_CONFIG, Python3_EXECUTABLE.
# ##############################################################################

function(bk_add_python_command)
    set(_oneValueArgs SCRIPT COMMENT)
    set(_multiValueArgs OUTPUT ARGS DEPENDS EXTRA_PYTHONPATH)
    cmake_parse_arguments(BKPY "" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})

    if(NOT BKPY_OUTPUT)
        message(FATAL_ERROR "bk_add_python_command: OUTPUT is required")
    endif()
    if(NOT BKPY_SCRIPT)
        message(FATAL_ERROR "bk_add_python_command: SCRIPT is required")
    endif()

    # PYTHONPATH: bk_py_libs first, then any caller-supplied dirs.
    set(_pythonpath "${NUTTX_CHIP_ABS_DIR}/tools/env_tools/bk_py_libs")
    foreach(_p IN LISTS BKPY_EXTRA_PYTHONPATH)
        set(_pythonpath "${_pythonpath}:${_p}")
    endforeach()

    # Create the parent directory of every output before the tool runs.
    set(_mkdir_cmds)
    set(_seen_dirs)
    foreach(_out IN LISTS BKPY_OUTPUT)
        get_filename_component(_dir "${_out}" DIRECTORY)
        if(_dir AND NOT _dir IN_LIST _seen_dirs)
            list(APPEND _seen_dirs "${_dir}")
            list(APPEND _mkdir_cmds COMMAND ${CMAKE_COMMAND} -E make_directory "${_dir}")
        endif()
    endforeach()

    # env_setup.sh is generated by environment.py via environment_setup_helper
    # (see chips/CMakeLists.txt).  Source it to inject the bk_sdk variables
    # (PROJECT_DIR, PROJECT_BUILD_DIR, ARMINO_SOC_NAME, PROJECT_NAME) into the
    # shell, then run the tool with PYTHONPATH set inline (environment.py does
    # not write PYTHONPATH into the shell script).
    set(_env_setup_sh "${CMAKE_BINARY_DIR}/env/env_setup.sh")

    # BKPY_ARGS is a CMake list; join with spaces so it expands correctly in
    # the bash -c string.
    string(REPLACE ";" " " _bkpy_args_str "${BKPY_ARGS}")

    add_custom_command(
        OUTPUT ${BKPY_OUTPUT}
        ${_mkdir_cmds}
        COMMAND 
            bash -c "source ${_env_setup_sh} && PYTHONPATH=${_pythonpath} ${Python3_EXECUTABLE} ${BKPY_SCRIPT} ${_bkpy_args_str}"
        DEPENDS ${BKPY_SCRIPT} ${BKPY_DEPENDS} environment_setup_helper
        COMMENT "${BKPY_COMMENT}"
        VERBATIM
    )
endfunction()
